#!/usr/bin/env python3
"""
Script to map AWS Audit Manager evidence sources to AWS Config rules.
Takes a framework JSON file (from get_framework_controls.py) and maps
AWS_Config and AWS_Security_Hub evidence sources to actual Config rules.

For AWS_Config sources: Maps the managed rule identifier to Config rules in your account.
For AWS_Security_Hub sources: Maps the security control ID to Config rules using a
    specified Security Hub standard controls JSON file (generated by security-standard-controls/get_standard_controls.py).
    AWS_Security_Hub sources are only mapped if --security-hub-file is provided.
"""

import argparse
import glob
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone

import boto3
from botocore.exceptions import ClientError, NoCredentialsError


def load_security_hub_control_mappings_from_file(security_hub_file: str) -> dict:
    """
    Load Security Hub control to Config rule mappings from a single JSON file.

    Args:
        security_hub_file: Path to a security hub standard controls JSON file
                          (e.g., aws-foundational-security-best-practices-v100.json)

    Returns:
        Dictionary mapping security_control_id to config_rule name
    """
    mappings = {}

    try:
        print(f"Loading Security Hub control mappings from: {security_hub_file}")
        with open(security_hub_file, "r", encoding="utf-8") as f:
            data = json.load(f)

        standard_name = data.get("standard_name", "Unknown")
        print(f"  Standard: {standard_name}")

        for control in data.get("controls", []):
            security_control_id = control.get("security_control_id")
            config_rule = control.get("config_rule")

            if security_control_id and config_rule:
                mappings[security_control_id] = config_rule

        print(f"  Loaded {len(mappings)} Security Hub control -> Config rule mappings")

    except FileNotFoundError:
        print(f"  Error: Security Hub standard file not found: {security_hub_file}")
    except Exception as e:
        print(f"  Warning: Could not load {security_hub_file}: {e}")

    return mappings


def load_catalog_descriptions_from_file(catalog_file: str) -> dict:
    """
    Load control descriptions from a cached Control Catalog JSON file.

    Args:
        catalog_file: Path to the cached catalog file (from export_control_catalog.py)

    Returns:
        Dictionary mapping Config rule identifier to description
    """
    descriptions = {}

    try:
        print(f"Loading control descriptions from cached catalog: {catalog_file}")
        with open(catalog_file, "r", encoding="utf-8") as f:
            catalog_data = json.load(f)

        controls = catalog_data.get("controls", {})
        for identifier, control in controls.items():
            if control.get("description"):
                descriptions[identifier] = control["description"]

        print(f"  Found descriptions for {len(descriptions)} Config rule identifiers")

    except FileNotFoundError:
        print(f"  Warning: Catalog file not found: {catalog_file}")
    except Exception as e:
        print(f"  Warning: Could not load catalog file: {e}")

    return descriptions


def get_control_catalog_descriptions(region: str = None) -> dict:
    """
    Fetch control descriptions from the AWS Controls Catalog API.

    Args:
        region: AWS region (optional)

    Returns:
        Dictionary mapping Config rule identifier to description
    """
    client_kwargs = {}
    if region:
        client_kwargs["region_name"] = region

    client = boto3.client("controlcatalog", **client_kwargs)

    descriptions = {}

    print("Fetching control descriptions from Controls Catalog...")
    try:
        paginator = client.get_paginator("list_controls")

        for page in paginator.paginate(MaxResults=100):
            for control in page.get("Controls", []):
                impl = control.get("Implementation", {})
                impl_type = impl.get("Type", "")
                identifier = impl.get("Identifier", "")

                # Only get descriptions for Config rules
                if impl_type == "AWS::Config::ConfigRule" and identifier:
                    descriptions[identifier] = control.get("Description", "")

        print(f"  Found descriptions for {len(descriptions)} Config rule identifiers")

    except Exception as e:
        print(f"  Warning: Could not fetch from Controls Catalog: {e}")

    return descriptions


def load_config_rules_from_file(config_rules_file: str, catalog_descriptions: dict = None) -> dict:
    """
    Load Config rules from a cached JSON file.

    Args:
        config_rules_file: Path to the cached config rules file
        catalog_descriptions: Descriptions from Controls Catalog (optional)

    Returns:
        Dictionary mapping SourceIdentifier to list of Config rules
    """
    rules_by_identifier = defaultdict(list)
    catalog_descriptions = catalog_descriptions or {}

    try:
        print(f"Loading Config rules from cache: {config_rules_file}")
        with open(config_rules_file, "r", encoding="utf-8") as f:
            cached_data = json.load(f)

        rules_list = cached_data.get("rules", [])
        for rule in rules_list:
            source_identifier = rule.get("SourceIdentifier", "")
            if source_identifier:
                # Update description from catalog if available
                if source_identifier in catalog_descriptions:
                    rule["Description"] = catalog_descriptions[source_identifier]
                rules_by_identifier[source_identifier].append(rule)

        print(f"  Found {sum(len(v) for v in rules_by_identifier.values())} Config rules")
        print(f"  Covering {len(rules_by_identifier)} unique managed rule identifiers")

    except FileNotFoundError:
        print(f"  Warning: Config rules cache not found: {config_rules_file}")
    except Exception as e:
        print(f"  Warning: Could not load config rules cache: {e}")

    return dict(rules_by_identifier)


def save_config_rules_to_file(rules_by_identifier: dict, output_file: str):
    """
    Save Config rules to a JSON file for caching.

    Args:
        rules_by_identifier: Dictionary mapping SourceIdentifier to list of rules
        output_file: Path to save the cache file
    """
    # Flatten the rules into a list
    rules_list = []
    for identifier, rules in rules_by_identifier.items():
        rules_list.extend(rules)

    cache_data = {
        "exportedAt": datetime.now(timezone.utc).isoformat(),
        "totalRules": len(rules_list),
        "uniqueIdentifiers": len(rules_by_identifier),
        "rules": rules_list
    }

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(cache_data, f, indent=2)

    print(f"  Saved Config rules cache to: {output_file}")


def get_all_config_rules(region: str = None, catalog_descriptions: dict = None, save_to_file: str = None) -> dict:
    """
    Retrieve all Config rules and index them by SourceIdentifier.

    Args:
        region: AWS region (optional)
        catalog_descriptions: Descriptions from Controls Catalog (optional)
        save_to_file: Path to save cache file (optional)

    Returns:
        Dictionary mapping SourceIdentifier to list of Config rules
    """
    client_kwargs = {}
    if region:
        client_kwargs["region_name"] = region

    client = boto3.client("config", **client_kwargs)

    rules_by_identifier = defaultdict(list)
    catalog_descriptions = catalog_descriptions or {}

    print("Fetching AWS Config rules...")
    paginator = client.get_paginator("describe_config_rules")

    for page in paginator.paginate():
        for rule in page["ConfigRules"]:
            source = rule.get("Source", {})
            source_identifier = source.get("SourceIdentifier", "")

            if source_identifier:
                # Prefer Controls Catalog description, fall back to API description
                description = catalog_descriptions.get(source_identifier) or rule.get("Description", "")

                rules_by_identifier[source_identifier].append({
                    "ConfigRuleName": rule["ConfigRuleName"],
                    "SourceIdentifier": source_identifier,
                    "SourceOwner": source.get("Owner"),
                    "Description": description,
                    "ConfigRuleState": rule.get("ConfigRuleState"),
                    "ConfigRuleArn": rule.get("ConfigRuleArn")
                })

    print(f"  Found {sum(len(v) for v in rules_by_identifier.values())} Config rules")
    print(f"  Covering {len(rules_by_identifier)} unique managed rule identifiers")

    # Save to cache file if requested
    if save_to_file:
        save_config_rules_to_file(rules_by_identifier, save_to_file)

    return dict(rules_by_identifier)


def extract_config_evidence_sources(framework_data: dict) -> tuple:
    """
    Extract all AWS_Config and AWS_Security_Hub evidence sources from framework data.

    Args:
        framework_data: Framework JSON from get_framework_controls.py

    Returns:
        Tuple of (config_sources dict, security_hub_sources dict)
        - config_sources: mapping keywordValue to list of controls using it
        - security_hub_sources: mapping security control ID to list of controls using it
    """
    config_sources = defaultdict(list)
    security_hub_sources = defaultdict(list)

    for control_set in framework_data.get("controlSets", []):
        for control in control_set.get("controls", []):
            control_info = {
                "controlId": control.get("controlId"),
                "controlName": control.get("controlName"),
                "controlSetName": control_set.get("controlSetName")
            }

            for mapping_source in control.get("controlMappingSources", []):
                source_type = mapping_source.get("sourceType")

                # Check direct AWS_Config sources
                if source_type == "AWS_Config":
                    keyword = mapping_source.get("sourceKeyword", {})
                    keyword_value = keyword.get("keywordValue")
                    if keyword_value:
                        config_sources[keyword_value].append({
                            **control_info,
                            "sourceName": mapping_source.get("sourceName"),
                            "sourceType": "AWS_Config",
                            "sourceLevel": "direct"
                        })

                # Check direct AWS_Security_Hub sources
                elif source_type == "AWS_Security_Hub":
                    keyword = mapping_source.get("sourceKeyword", {})
                    keyword_value = keyword.get("keywordValue")
                    if keyword_value:
                        security_hub_sources[keyword_value].append({
                            **control_info,
                            "sourceName": mapping_source.get("sourceName"),
                            "sourceType": "AWS_Security_Hub",
                            "sourceLevel": "direct"
                        })

                # Check Core Control evidence sources
                for evidence_source in mapping_source.get("coreControlEvidenceSources", []):
                    es_source_type = evidence_source.get("sourceType")

                    if es_source_type == "AWS_Config":
                        keyword = evidence_source.get("sourceKeyword", {})
                        keyword_value = keyword.get("keywordValue")
                        if keyword_value:
                            config_sources[keyword_value].append({
                                **control_info,
                                "sourceName": mapping_source.get("sourceName"),
                                "coreControlSourceName": evidence_source.get("sourceName"),
                                "sourceType": "AWS_Config",
                                "sourceLevel": "coreControl"
                            })

                    elif es_source_type == "AWS_Security_Hub":
                        keyword = evidence_source.get("sourceKeyword", {})
                        keyword_value = keyword.get("keywordValue")
                        if keyword_value:
                            security_hub_sources[keyword_value].append({
                                **control_info,
                                "sourceName": mapping_source.get("sourceName"),
                                "coreControlSourceName": evidence_source.get("sourceName"),
                                "sourceType": "AWS_Security_Hub",
                                "sourceLevel": "coreControl"
                            })

    return dict(config_sources), dict(security_hub_sources)


def map_evidence_to_rules(framework_file: str, region: str = None, catalog_file: str = None, config_rules_file: str = None, save_config_rules: str = None, security_hub_file: str = None) -> dict:
    """
    Map framework evidence sources to Config rules.

    Args:
        framework_file: Path to framework JSON file
        region: AWS region (optional)
        catalog_file: Path to cached Control Catalog file (optional, avoids API calls)
        config_rules_file: Path to cached Config rules file (optional, avoids API calls)
        save_config_rules: Path to save Config rules cache (optional)
        security_hub_file: Path to Security Hub standard controls JSON file (optional).
                          If provided, AWS_Security_Hub sources will be mapped using this file.
                          If not provided, AWS_Security_Hub sources will be skipped.

    Returns:
        Mapping result dictionary
    """
    # Load framework data
    print(f"Loading framework from: {framework_file}")
    with open(framework_file, "r", encoding="utf-8") as f:
        framework_data = json.load(f)

    framework_name = framework_data.get("frameworkName", "Unknown")
    print(f"Framework: {framework_name}")

    # Extract evidence sources (both AWS_Config and AWS_Security_Hub)
    print("\nExtracting evidence sources from framework...")
    config_sources, security_hub_sources = extract_config_evidence_sources(framework_data)
    print(f"  Found {len(config_sources)} unique AWS_Config rule identifiers")
    print(f"  Found {len(security_hub_sources)} unique AWS_Security_Hub control IDs")

    # Load Security Hub control to Config rule mappings only if file is provided
    security_hub_mappings = {}
    if security_hub_file:
        print()
        security_hub_mappings = load_security_hub_control_mappings_from_file(security_hub_file)
    elif security_hub_sources:
        print("\n  Note: AWS_Security_Hub sources found but no --security-hub-file provided. Skipping Security Hub mapping.")

    # Get control descriptions - prefer cached file over API call
    print()
    if catalog_file:
        catalog_descriptions = load_catalog_descriptions_from_file(catalog_file)
    else:
        catalog_descriptions = get_control_catalog_descriptions(region)

    # Get Config rules - prefer cached file over API call
    print()
    if config_rules_file:
        config_rules = load_config_rules_from_file(config_rules_file, catalog_descriptions)
    else:
        config_rules = get_all_config_rules(region, catalog_descriptions, save_config_rules)

    # Build mapping
    print("\nMapping evidence sources to Config rules...")

    # Only count Security Hub sources if we're mapping them
    sec_hub_count = len(security_hub_sources) if security_hub_file else 0
    total_sources = len(config_sources) + sec_hub_count
    mapping_result = {
        "frameworkName": framework_name,
        "frameworkId": framework_data.get("frameworkId"),
        "securityHubStandardFile": security_hub_file,
        "mappings": [],
        "summary": {
            "totalEvidenceSourceIdentifiers": total_sources,
            "awsConfigSources": len(config_sources),
            "awsSecurityHubSources": sec_hub_count,
            "awsSecurityHubSourcesInFramework": len(security_hub_sources),
            "mappedToConfigRules": 0,
            "notMappedToConfigRules": 0,
            "totalConfigRulesMatched": 0
        }
    }

    mapped_count = 0
    not_mapped_count = 0
    total_rules_matched = 0

    # Map AWS_Config sources
    for keyword_value, controls in sorted(config_sources.items()):
        matching_rules = config_rules.get(keyword_value, [])

        mapping_entry = {
            "sourceType": "AWS_Config",
            "identifier": keyword_value,
            "controlsUsingThis": controls,
            "configRulesInAccount": matching_rules,
            "isMapped": len(matching_rules) > 0
        }

        mapping_result["mappings"].append(mapping_entry)

        if matching_rules:
            mapped_count += 1
            total_rules_matched += len(matching_rules)
        else:
            not_mapped_count += 1

    # Map AWS_Security_Hub sources (only if security_hub_file was provided)
    if security_hub_file and security_hub_mappings:
        for control_id, controls in sorted(security_hub_sources.items()):
            config_rule_name = security_hub_mappings.get(control_id)

            # Build a rule entry similar to AWS_Config mappings
            matching_rules = []
            if config_rule_name:
                matching_rules = [{
                    "ConfigRuleName": config_rule_name,
                    "SourceIdentifier": f"SecurityHub:{control_id}",
                    "SourceOwner": "AWS_Security_Hub",
                    "Description": f"Security Hub control {control_id}"
                }]

            mapping_entry = {
                "sourceType": "AWS_Security_Hub",
                "identifier": control_id,
                "controlsUsingThis": controls,
                "configRulesInAccount": matching_rules,
                "isMapped": len(matching_rules) > 0
            }

            mapping_result["mappings"].append(mapping_entry)

            if matching_rules:
                mapped_count += 1
                total_rules_matched += len(matching_rules)
            else:
                not_mapped_count += 1

    mapping_result["summary"]["mappedToConfigRules"] = mapped_count
    mapping_result["summary"]["notMappedToConfigRules"] = not_mapped_count
    mapping_result["summary"]["totalConfigRulesMatched"] = total_rules_matched

    return mapping_result


def print_summary(mapping_result: dict):
    """Print a human-readable summary of the mapping."""
    summary = mapping_result["summary"]

    print("\n" + "=" * 80)
    print("MAPPING SUMMARY")
    print("=" * 80)
    print(f"Framework: {mapping_result['frameworkName']}")
    print(f"Total evidence source identifiers: {summary['totalEvidenceSourceIdentifiers']}")
    print(f"  - AWS_Config sources: {summary.get('awsConfigSources', 'N/A')}")
    print(f"  - AWS_Security_Hub sources: {summary.get('awsSecurityHubSources', 'N/A')}")
    print(f"Mapped to Config rules: {summary['mappedToConfigRules']}")
    print(f"NOT mapped (no matching rules): {summary['notMappedToConfigRules']}")
    print(f"Total Config rules matched: {summary['totalConfigRulesMatched']}")

    # Show unmapped identifiers by type
    unmapped = [m for m in mapping_result["mappings"] if not m["isMapped"]]
    if unmapped:
        print(f"\n{'=' * 80}")
        print("UNMAPPED IDENTIFIERS (no Config rules found)")
        print("=" * 80)

        unmapped_config = [m for m in unmapped if m.get("sourceType") == "AWS_Config"]
        unmapped_sechub = [m for m in unmapped if m.get("sourceType") == "AWS_Security_Hub"]

        if unmapped_config:
            print("\n  AWS_Config:")
            for m in unmapped_config:
                print(f"    - {m['identifier']}")

        if unmapped_sechub:
            print("\n  AWS_Security_Hub:")
            for m in unmapped_sechub:
                print(f"    - {m['identifier']}")

    # Show mapped identifiers with their rules
    mapped = [m for m in mapping_result["mappings"] if m["isMapped"]]
    if mapped:
        print(f"\n{'=' * 80}")
        print("MAPPED IDENTIFIERS")
        print("=" * 80)
        for m in mapped[:10]:  # Show first 10
            source_type = m.get("sourceType", "Unknown")
            print(f"\n  [{source_type}] {m['identifier']}:")
            for rule in m["configRulesInAccount"]:
                print(f"    -> {rule['ConfigRuleName']}")

        if len(mapped) > 10:
            print(f"\n  ... and {len(mapped) - 10} more (see output file for full list)")


def main():
    parser = argparse.ArgumentParser(
        description="Map AWS Audit Manager evidence sources to AWS Config rules"
    )
    parser.add_argument(
        "framework_file",
        help="Path to framework JSON file (output from get_framework_controls.py)"
    )
    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: <framework_file>_config_mapping.json)",
        default=None
    )
    parser.add_argument(
        "-r", "--region",
        help="AWS region (uses default region if not specified)",
        default=None
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print full JSON to stdout instead of file"
    )
    parser.add_argument(
        "--catalog-file",
        help="Path to cached Control Catalog JSON file (avoids API calls)",
        default=None
    )
    parser.add_argument(
        "--config-rules-file",
        help="Path to cached Config rules JSON file (avoids API calls)",
        default=None
    )
    parser.add_argument(
        "--save-config-rules",
        help="Path to save Config rules cache for future use",
        default=None
    )
    parser.add_argument(
        "--security-hub-file",
        help="Path to Security Hub standard controls JSON file (e.g., aws-foundational-security-best-practices-v100.json). "
             "If provided, AWS_Security_Hub sources will be mapped using this file. "
             "If not provided, AWS_Security_Hub sources will be skipped.",
        default=None
    )

    args = parser.parse_args()

    try:
        mapping_result = map_evidence_to_rules(
            args.framework_file,
            args.region,
            args.catalog_file,
            args.config_rules_file,
            args.save_config_rules,
            args.security_hub_file
        )

        if args.stdout:
            print(json.dumps(mapping_result, indent=2))
        else:
            output_file = args.output
            if not output_file:
                base_name = args.framework_file.rsplit(".", 1)[0]
                output_file = f"{base_name}_config_mapping.json"

            with open(output_file, "w", encoding="utf-8") as f:
                json.dump(mapping_result, f, indent=2)

            print_summary(mapping_result)
            print(f"\nFull mapping written to: {output_file}")

    except FileNotFoundError:
        print(f"Error: Framework file not found: {args.framework_file}", file=sys.stderr)
        sys.exit(1)
    except NoCredentialsError:
        print("Error: AWS credentials not found. Please configure your AWS credentials.", file=sys.stderr)
        sys.exit(1)
    except ClientError as e:
        error_code = e.response["Error"]["Code"]
        error_message = e.response["Error"]["Message"]
        print(f"AWS API Error ({error_code}): {error_message}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
